name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: git fetch origin "$BASE_COMMIT_SHA"
      
      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build