name: Code Check

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: git fetch origin "$BASE_COMMIT_SHA"
      
      - name: Install dependencies 
        run: bun install

      - name: Format code
        run: bun run format

      - name: Type check
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun run test
